CREATE DATABASE IF NOT EXISTS GT;

USE GT;

CREATE TABLE IF NOT EXISTS EMPRESES
   (EMPRESA_ID INT PRIMARY KEY,
    CIF VARCHAR(30) NOT NULL UNIQUE,
    EMPRESA_NOM VARCHAR(30) NOT NULL,
    DIRECCIO VARCHAR(50)
    );

CREATE TABLE IF NOT EXISTS DEPARTMENTS
   (DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NOM VARCHAR(30) NOT NULL,
    EMPRESA_ID INT,
    GERENT_ID INT
    );

CREATE TABLE IF NOT EXISTS EMPLEATS
   (EMPLEAT_ID INT PRIMARY KEY,
    EMPLEAT_NOM VARCHAR(20) NOT NULL,
    EMPLEAT_ROL VARCHAR(25),
    DNI VARCHAR(25) NOT NULL UNIQUE,
    CORREU VARCHAR(25) NOT NULL UNIQUE,
    TELEFON VARCHAR(20),
    DEPARTMENT_ID INT,
    GERENT_ID INT
  );

CREATE TABLE IF NOT EXISTS TASQUES
   (TASCA_ID INT NOT NULL,
    TASCA_NOM VARCHAR(30),
    DESCRIPCIO VARCHAR(100),
    DEPARTMENT_ID INT,
    EMPLEAT_ID INT
  );

CREATE TABLE IF NOT EXISTS HISTORICS
   (EMPLEAT_ID NOT NULL,
    TASCA_ID NOT NULL,
    DATA_INICI VARCHAR(10) NOT NULL,
    DATA_FI VARCHAR(10),
     PRIMARY KEY(EMPLEAT_ID, TASCA_ID)
  );